# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  android: circleci/android@0.2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/android
    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8

  ios-executor:
    working_directory: ~/ios
    macos:
      xcode: 11.4.0

jobs:
  test-ios:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Install pods
          command: pod install
          working_directory: ios/PurchasesHybridCommon
      - run:
          name: Run ios tests
          command: fastlane scan
          working_directory: ios/PurchasesHybridCommon
          environment:
            SCAN_SCHEME: PurchasesHybridCommonTests
      - store_test_results:
          working_directory: ios/PurchasesHybridCommon
          path: test_output
      - store_artifacts:
          working_directory: ios/PurchasesHybridCommon
          path: test_output
          destination: scan-output
      

  test-android:
    executor: android-executor
    steps:
      - checkout
      - android/accept-licenses
      - run:
          name: Run Tests
          command: ./gradlew lint test
          working_directory: android
      - store_artifacts:
          path: build/reports
          working_directory: android
      - store_test_results:
          path: build/test-results
          working_directory: android


workflows:
  version: 2
  build-test:
    jobs:
      - test-ios
      - test-android
      